name: Regression Test

on:
  pull_request:
    branches:
      - main
    paths:
      - toolsaf/**
      - tests/**
      - regression_tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Run existing statements
      run: |
        python regression_tests/run_statements.py regression_tests/test_setup.json
